[tool.poetry]
name = "hyprshade"
version = "0.1.0"
description = ""
authors = ["John Bernard <loqusion@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "main", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.3"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
twine = "^4.0.2"
flake8 = "^6.0.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
