name: Publish PKGBUILD to AUR

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: "aur"
  cancel-in-progress: true

jobs:
  aur-update:
    runs-on: ubuntu-latest
    environment: AUR
    steps:
      - uses: actions/checkout@v3
      - uses: loqusion/aur-publish-action@v1
        with:
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          package_name: hyprshade
