name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pdm sync -d -G test
      - name: Lint with ruff
        run: |
          pdm run -v ruff check src
      - name: Check types with mypy
        run: |
          pdm run -v mypy src
      - name: Test with pytest
        run: |
          pdm run -v pytest -m "not hyprland" tests
