name: Tests

on:
  push:
    branches: ["main", "ci"]
  pull_request:
    branches: ["main", "ci"]

jobs:
  Testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup rye
        uses: sksat/setup-rye@v0.18.0
        with:
          version: 0.29.0
      - name: Install dependencies with rye
        run: |
          rye sync --features test
      - name: Lint
        run: |
          rye run lint:style
          rye run lint:typing
      - name: Test
        run: |
          rye run test:pytest
