name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: PyPI
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
      - name: Publish package
        run: pdm publish
