name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: PyPI
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup rye
        uses: sksat/setup-rye@v0.7.0
        with:
          version: 0.13.0
      - name: Install dependencies with rye
        run: |
          rye sync
      - name: Build
        # NOTE: `rye build --wheel` must be run in order to include the .data files (for some reason)
        run: |
          rye build --wheel
          rye build --sdist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
