name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: PyPI
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup rye
        uses: sksat/setup-rye@v0.7.0
        with:
          version: 0.13.0
      - name: Install dependencies with rye
        run: |
          rye sync
      - name: Build
        run: |
          rye build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  aur-update:
    name: publish to AUR
    needs: release-pypi
    runs-on: ubuntu-latest
    environment: AUR
    concurrency:
      group: "aur"
      cancel-in-progress: true
    steps:
      - name: Sleep to account for delay in PyPI package availability
        run: sleep 120
      - uses: actions/checkout@v4
      - uses: loqusion/aur-publish-action@main
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          package-name: hyprshade
